#!/usr/bin/env python

# htopy - A Python interface generator for C codes
# Copyright (C) 2020 Gajanan Choudhary (Email: gajananchoudhary91@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import os
import sys
import importlib

from htopy.htopy_class import Htopy
from htopy.parse_args import parse_args
from .import_htopy_input import import_htopy_input

gpl_print= (
"""\
______________________________________________________________________
htopy - A Python interface generator for C codes
Copyright (C) 2020 Gajanan Choudhary (gajananchoudhary91@gmail.com)

This program comes with ABSOLUTELY NO WARRANTY. This is a free
software, and you are welcome to redistribute it under the
conditions given in the GNU General Public License version 3.0.
For more details, visit https://www.gnu.org/licenses/.

Although the htopy source code is licensed under GPL v3.0, the
output generated by your (C header) input to htopy is free to use
as per the your requirement. The output may be governed by some
other license, such as the license of the input C source code, or
something else depending on your situation. It is up to you to
determine the license governign the output.

Thanks for using and supporting this program!
______________________________________________________________________
""")

################################################################################
def main():
    """Main/top-level function of htopy."""

    ######################
    print(gpl_print)

    if sys.version_info<(2,7,0) or sys.version_info>(2,9,9):
        sys.stderr.write("You need python 2.7+ (not 3+) to run this project\n")
        sys.exit(1)

    try:
        args = parse_args()
    except:
        sys.stderr.write("Error while parsing command line arguments.\n")
        sys.exit(1)

    print

    ######################
    htopy_obj = Htopy()

    # Import the user-supplied Python file as a module.
    # To Do: validate the variables in the imported module.
    htopy_obj.htopy_input = import_htopy_input(args.input,args.path)

    htopy_obj.initialize()

    htopy_obj.run()

    htopy_obj.finalize()

################################################################################
if __name__=="__main__":
    main();

